---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2a
spec:
  securityGroups: 
    - sg-0d0ca9fdad99e3cc1
  subnet: subnet-09d09754e6a9f25e2
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2c
spec:
  securityGroups: 
    - sg-0d0ca9fdad99e3cc1
  subnet: subnet-09df7a873d0304bed
